const EMAIL_TMPL = `Dear %%TD_NAMES%%,

As my local TD for %%AREA%% you may be aware of the ongoing series of demonstrations in Hong Kong known as the Anti-Extradition Law Amendment Bill Movement, which began with the aim of opposing the introduction a new Extradition Law proposed by the Hong Kong government. During these peaceful protests there has been brutal repression on the part of the Chinese state. This includes brutal beatings and sexual violence being inflicted on protestors by the Hong Kong police as well as the imprisonment of over 1,600 people.

In light of this I wish to highlight the close business ties between Ireland and China. Numerous Irish businesses in the country in different industries are backed by Chinese investments, such as pharma and medical. This investment is increasing with the support from IDA Ireland. There have also been deals done with Chinese State companies, such as the licence given to the China National Offshore Oil Company to drill off the coast of Kerry. I am deeply concerned about China’s growing interest in the economy and the Irish government’s willingness to do business with the brutal tyranny that is the Chinese State.

Moreover, I would like to raise concerns about the influence of Confucius Institute - a Chinese state-backed organisation in UCD. More than 450 Confucius Institutes have been set up by the Chinese government in partnership with universities around the world. While they are sometimes compared to cultural organisations such as the British Council and France’s Alliance Française, the Chinese model is unique in being directly run by the Chinese state and being located only on university or college campuses. UCD agreed with the Chinese government to jointly operate a Confucius Institute on the Belfield campus in 2006 until at least 2066. The college has recently established a course on Chinese studies which it said “offers a wide range of modules” to help students gain an “understanding and knowledge of China”. The modules cover society, culture, politics, law, economy and doing business in China. It is completely inappropriate for UCD to allow a Chinese state entity to oversee teaching about Chinese politics and society. Confucius Institutes are controlled by the Chinese Language Council International which is ultimately overseen by the Chinese Communist Party’s (CCP) Central Propaganda Department. Educational institutions across the United States and Australia have the same concern and appear to be reconsidering the relationship with Confucius Institutes and as of August, 37 public schools have closed down the Confucius Institutes around the world. Why does the Irish government allow a Communist propaganda machine into our public university?

I hope you can review these issues for yourself and in light of how serious the problems have become, will take action to force a change in the policies surrounding the Ireland - China relationship. I would be very interested in hearing from you with regards to your views on this matter and what you might be able to do about it.


Yours sincerely,
>>>[Insert your name]<<<`;

export default EMAIL_TMPL;
